python launch.py --config configs/edit-dc.yaml --train --gpu 0 \
    system.seg_prompt="a face" \
    exp_root_dir=outputs/face \
    trainer.max_steps=1500 \
    system.prompt_processor.prompt="Turn him into the Tolkien Elf" \
    system.dds_target_prompt_processor.prompt="Turn him into the Tolkien Elf" \
    system.dds_source_prompt_processor.prompt="a photo of a face" \
    system.max_densify_percent=0.01 \
    system.anchor_weight_init_g0=0.05 \
    system.anchor_weight_init=0.1 \
    system.anchor_weight_multiplier=1.3 \
    system.gs_lr_scaler=1 \
    system.gs_final_lr_scaler=1 \
    system.color_lr_scaler=1 \
    system.opacity_lr_scaler=1 \
    system.scaling_lr_scaler=1 \
    system.rotation_lr_scaler=1 \
    system.loss.lambda_anchor_color=5 \
    system.loss.lambda_anchor_geo=5 \
    system.loss.lambda_anchor_scale=5 \
    system.loss.lambda_anchor_opacity=5 \
    system.densify_from_iter=100 \
    system.densify_until_iter=1201 \
    system.densification_interval=100 \
    system.second_guidance.chi=0.075 \
    system.second_guidance.delta=0.05 \
    system.second_guidance.gamma=0.2 \
    data.source=../dataset/face \
    system.gs_source=../scene/face/point_cloud/iteration_30000/point_cloud.ply

python launch.py --config configs/edit-dc.yaml --train --gpu 0 \
    system.seg_prompt="a face" \
    exp_root_dir=outputs/face \
    trainer.max_steps=1500 \
    system.prompt_processor.prompt="Turn him into Emma Watson" \
    system.dds_target_prompt_processor.prompt="Turn him into Emma Watson" \
    system.dds_source_prompt_processor.prompt="a photo of a face" \
    system.max_densify_percent=0.01 \
    system.anchor_weight_init_g0=0.05 \
    system.anchor_weight_init=0.1 \
    system.anchor_weight_multiplier=1.3 \
    system.gs_lr_scaler=1 \
    system.gs_final_lr_scaler=1 \
    system.color_lr_scaler=1 \
    system.opacity_lr_scaler=1 \
    system.scaling_lr_scaler=1 \
    system.rotation_lr_scaler=1 \
    system.loss.lambda_anchor_color=5 \
    system.loss.lambda_anchor_geo=5 \
    system.loss.lambda_anchor_scale=5 \
    system.loss.lambda_anchor_opacity=5 \
    system.densify_from_iter=100 \
    system.densify_until_iter=1201 \
    system.densification_interval=100 \
    system.second_guidance.chi=0.075 \
    system.second_guidance.delta=0.05 \
    system.second_guidance.gamma=0.2 \
    data.source=../dataset/face \
    system.gs_source=../scene/face/point_cloud/iteration_30000/point_cloud.ply

python launch.py --config configs/edit-dc.yaml --train --gpu 0 \
    system.seg_prompt="a face" \
    exp_root_dir=outputs/face \
    trainer.max_steps=1500 \
    system.prompt_processor.prompt="Turn him into Elon Musk" \
    system.dds_target_prompt_processor.prompt="Turn him into Elon Musk" \
    system.dds_source_prompt_processor.prompt="a photo of a face" \
    system.max_densify_percent=0.01 \
    system.anchor_weight_init_g0=0.05 \
    system.anchor_weight_init=0.1 \
    system.anchor_weight_multiplier=1.3 \
    system.gs_lr_scaler=1 \
    system.gs_final_lr_scaler=1 \
    system.color_lr_scaler=1 \
    system.opacity_lr_scaler=1 \
    system.scaling_lr_scaler=1 \
    system.rotation_lr_scaler=1 \
    system.loss.lambda_anchor_color=5 \
    system.loss.lambda_anchor_geo=5 \
    system.loss.lambda_anchor_scale=5 \
    system.loss.lambda_anchor_opacity=5 \
    system.densify_from_iter=100 \
    system.densify_until_iter=1201 \
    system.densification_interval=100 \
    system.second_guidance.chi=0.075 \
    system.second_guidance.delta=0.05 \
    system.second_guidance.gamma=0.2 \
    data.source=../dataset/face \
    system.gs_source=../scene/face/point_cloud/iteration_30000/point_cloud.ply

python launch.py --config configs/edit-dc.yaml --train --gpu 0 \
    system.seg_prompt="a face" \
    exp_root_dir=outputs/face \
    trainer.max_steps=1500 \
    system.prompt_processor.prompt="Turn him into an Einstein" \
    system.dds_target_prompt_processor.prompt="Turn him into an Einstein" \
    system.dds_source_prompt_processor.prompt="a photo of a face" \
    system.max_densify_percent=0.01 \
    system.anchor_weight_init_g0=0.05 \
    system.anchor_weight_init=0.1 \
    system.anchor_weight_multiplier=1.3 \
    system.gs_lr_scaler=1 \
    system.gs_final_lr_scaler=1 \
    system.color_lr_scaler=1 \
    system.opacity_lr_scaler=1 \
    system.scaling_lr_scaler=1 \
    system.rotation_lr_scaler=1 \
    system.loss.lambda_anchor_color=5 \
    system.loss.lambda_anchor_geo=5 \
    system.loss.lambda_anchor_scale=5 \
    system.loss.lambda_anchor_opacity=5 \
    system.densify_from_iter=100 \
    system.densify_until_iter=1201 \
    system.densification_interval=100 \
    system.second_guidance.chi=0.075 \
    system.second_guidance.delta=0.05 \
    system.second_guidance.gamma=0.2 \
    data.source=../dataset/face \
    system.gs_source=../scene/face/point_cloud/iteration_30000/point_cloud.ply

python launch.py --config configs/edit-dc.yaml --train --gpu 0 \
    system.seg_prompt="a face" \
    exp_root_dir=outputs/face \
    trainer.max_steps=1500 \
    system.prompt_processor.prompt="Give him a mustache" \
    system.dds_target_prompt_processor.prompt="Give him a mustache" \
    system.dds_source_prompt_processor.prompt="a photo of a face" \
    system.max_densify_percent=0.01 \
    system.anchor_weight_init_g0=0.05 \
    system.anchor_weight_init=0.1 \
    system.anchor_weight_multiplier=1.3 \
    system.gs_lr_scaler=1 \
    system.gs_final_lr_scaler=1 \
    system.color_lr_scaler=1 \
    system.opacity_lr_scaler=1 \
    system.scaling_lr_scaler=1 \
    system.rotation_lr_scaler=1 \
    system.loss.lambda_anchor_color=5 \
    system.loss.lambda_anchor_geo=5 \
    system.loss.lambda_anchor_scale=5 \
    system.loss.lambda_anchor_opacity=5 \
    system.densify_from_iter=100 \
    system.densify_until_iter=1201 \
    system.densification_interval=100 \
    system.second_guidance.chi=0.075 \
    system.second_guidance.delta=0.05 \
    system.second_guidance.gamma=0.2 \
    data.source=../dataset/face \
    system.gs_source=../scene/face/point_cloud/iteration_30000/point_cloud.ply

python launch.py --config configs/edit-dc.yaml --train --gpu 0 \
    system.seg_prompt="a face" \
    exp_root_dir=outputs/face \
    trainer.max_steps=1500 \
    system.prompt_processor.prompt="Turn him into Leonardo Dicaprio" \
    system.dds_target_prompt_processor.prompt="Turn him into Leonardo Dicaprio" \
    system.dds_source_prompt_processor.prompt="a photo of a face" \
    system.max_densify_percent=0.01 \
    system.anchor_weight_init_g0=0.05 \
    system.anchor_weight_init=0.1 \
    system.anchor_weight_multiplier=1.3 \
    system.gs_lr_scaler=1 \
    system.gs_final_lr_scaler=1 \
    system.color_lr_scaler=1 \
    system.opacity_lr_scaler=1 \
    system.scaling_lr_scaler=1 \
    system.rotation_lr_scaler=1 \
    system.loss.lambda_anchor_color=5 \
    system.loss.lambda_anchor_geo=5 \
    system.loss.lambda_anchor_scale=5 \
    system.loss.lambda_anchor_opacity=5 \
    system.densify_from_iter=100 \
    system.densify_until_iter=1201 \
    system.densification_interval=100 \
    system.second_guidance.chi=0.075 \
    system.second_guidance.delta=0.05 \
    system.second_guidance.gamma=0.2 \
    data.source=../dataset/face \
    system.gs_source=../scene/face/point_cloud/iteration_30000/point_cloud.ply

python launch.py --config configs/edit-dc.yaml --train --gpu 0 \
    system.seg_prompt="a face" \
    exp_root_dir=outputs/face \
    trainer.max_steps=1500 \
    system.prompt_processor.prompt="Turn his face into a skull" \
    system.dds_target_prompt_processor.prompt="Turn his face into a skull" \
    system.dds_source_prompt_processor.prompt="a photo of a face" \
    system.max_densify_percent=0.01 \
    system.anchor_weight_init_g0=0.05 \
    system.anchor_weight_init=0.1 \
    system.anchor_weight_multiplier=1.3 \
    system.gs_lr_scaler=1 \
    system.gs_final_lr_scaler=1 \
    system.color_lr_scaler=1 \
    system.opacity_lr_scaler=1 \
    system.scaling_lr_scaler=1 \
    system.rotation_lr_scaler=1 \
    system.loss.lambda_anchor_color=5 \
    system.loss.lambda_anchor_geo=5 \
    system.loss.lambda_anchor_scale=5 \
    system.loss.lambda_anchor_opacity=5 \
    system.densify_from_iter=100 \
    system.densify_until_iter=1201 \
    system.densification_interval=100 \
    system.second_guidance.chi=0.075 \
    system.second_guidance.delta=0.05 \
    system.second_guidance.gamma=0.2 \
    data.source=../dataset/face \
    system.gs_source=../scene/face/point_cloud/iteration_30000/point_cloud.ply